- Effect: Allow
  Action:
    - dynamodb:CreateTable
    - dynamodb:Query
    - dynamodb:Scan
    - dynamodb:GetItem
    - dynamodb:PutItem
    - dynamodb:UpdateItem
    - dynamodb:DeleteItem
    - dynamodb:DescribeTable
  Resource:
    - Fn::GetAtt: [UsersTable, Arn]