- Effect: Allow
  Action:
    - dynamodb:CreateTable
    - dynamodb:Query
    - dynamodb:Scan
    - dynamodb:GetItem
    - dynamodb:PutItem
    - dynamodb:UpdateItem
    - dynamodb:DeleteItem
    - dynamodb:DescribeTable
  Resource:
    - Fn::GetAtt: [UsersTable, Arn]
    - Fn::Sub: "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${UsersTable}/index/EmailIndex"
    - Fn::GetAtt: [TeachersTable, Arn]
    - Fn::Sub: "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TeachersTable}/index/EmailIndex"