# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: saurabftechiz
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: exp-dynamo-app
# "service" is the name of this project. This will also be added to your AWS resource names.
service: exp-dynamo

stages:
  default:
    params:
      tableName: "ExpDyno-${sls:stage}"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  iam:
    role:
      statements: ${file(src/Config/iamRoleStatements.yml)}
  environment: ${file(src/Config/environment.yml)}

functions:
  ${file(src/Functions/httpFunctions.yml)}

resources:
  ${file(src/Resources/dynamoTables.yml)}

plugins:
  - serverless-offline
  
build:
  esbuild:
    minify: true

package:
  individually: true